<?php

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Add concept field to contract entity.
 */
function solana_contracts_update_8001() {
  $storage_definition = BaseFieldDefinition::create('string')
    ->setLabel(t('Concept'))
    ->setDescription(t('The concept of the contract.'))
    ->setRequired(FALSE)
    ->setDisplayOptions('view', [
      'label' => 'above',
      'type' => 'string',
      'weight' => -4,
    ])
    ->setDisplayOptions('form', [
      'type' => 'string_textfield',
      'weight' => -4,
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE);

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('concept', 'contract', 'solana_contracts', $storage_definition);
}
