<?php

namespace Drupal\solana_contracts\Entity;

use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Defines the Solana Signature entity.
 *
 * @ContentEntityType(
 * id = "solana_signature",
 * label = @Translation("Solana Signature"),
 * handlers = {
 * "view_builder" = "Drupal\Core\Entity\EntityViewBuilder",
 * "list_builder" = "Drupal\Core\Entity\EntityListBuilder",
 * "views_data" = "Drupaliews\EntityViewsData",
 * },
 * base_table = "solana_signature",
 * admin_permission = "administer solana contracts",
 * entity_keys = {
 * "id" = "id",
 * "uuid" = "uuid",
 * },
 * )
 */
class SolanaSignature extends ContentEntityBase {

  /**
   * {@inheritdoc}
   */
  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {
    $fields = parent::baseFieldDefinitions($entity_type);

    // Reference to the contract being signed.
    $fields['contract_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Contract'))
      ->setSetting('target_type', 'solana_contract')
      ->setRequired(TRUE);

    // The user who signed.
    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('User'))
      ->setSetting('target_type', 'user')
      ->setRequired(TRUE);

    // Date of signature.
    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(t('Signature Date'));

    // The actual cryptographic signature from the wallet.
    $fields['digital_signature'] = BaseFieldDefinition::create('string_long')
      ->setLabel(t('Digital Signature'))
      ->setDescription(t('The signature hash generated by the Solana wallet.'))
      ->setRequired(TRUE);

    // Status of this specific signature.
    $fields['status'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Signature Status'))
      ->setSettings([
        'allowed_values' => [
          'pending' => t('Pending'),
          'signed' => t('Signed'),
          'rejected' => t('Rejected'),
        ],
      ])
      ->setDefaultValue('signed');

    return $fields;
  }

}